### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by hissssst** [johnhamelink/hexdocs_docset_api#8]
I've created a fork with extra features and I am planning to maintain it. What License should I provide? What about AGPLv3 with mentioning you and me?

**Comment by johnhamelink** [comment]
Brilliant, I'll definitely use your fork & contribute back if I find a reason to! AGPLv3 works well for me. Please link to it so I can direct users to your fork.

Thanks for reaching out!

**Comment by hissssst** [comment]
Sure, here it is: https://github.com/hissssst/hexdocs_docset_api/
